version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGODB_UI_PORT}:${MONGODB_UI_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}